# https://help.nextcloud.com/t/docker-compose-for-nextcloud-collabora-traefik/127733/6
# docker-compose.yml
version: '3.9'

services:
  traefik:
    image: traefik:v2.8.5
    container_name: traefik
    hostname: traefik
    restart: always
    networks:
      default:
        aliases:
          - ${COLLABORA_HOST_NAME}
          - ${NEXTCLOUD_HOST_NAME}
    environment:
      - TZ=${TZ}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log
      - /data/traefik:/data/traefik
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml
    env_file:
      - traefik.env
    command:
      # default location to search for the static configuration file
      - --providers.file.filename=/etc/traefik/traefik.yaml
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.entryPoints=traefik'
      - 'traefik.http.routers.dashboard.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`) || PathPrefix(`/debug`)'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}'      
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    volumes:
      - /data/nextcloud:/var/www/html
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEPROTOCOL=${OVERWRITEPROTOCOL}
      - NC_default_phone_region=${NC_default_phone_region}
      - NEXTCLOUD_HOST_NAME=${NEXTCLOUD_HOST_NAME}
    depends_on:
      - postgres
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.tls=true'
      - 'traefik.http.routers.nextcloud.tls.certresolver=myresolver'
      - 'traefik.http.routers.nextcloud.entrypoints=websecure'
      - 'traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOST_NAME}`)'
      - 'traefik.http.routers.nextcloud.middlewares=nextcloud-dav,nextcloud-header'
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.nextcloud-dav.redirectRegex.regex=https://(.*)/.well-known/(card|cal)dav'
      - 'traefik.http.middlewares.nextcloud-dav.redirectRegex.replacement=https://$${1}/remote.php/dav/'
      - 'traefik.http.middlewares.nextcloud-dav.redirectRegex.permanent=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.referrerPolicy=no-referrer'
      - 'traefik.http.middlewares.nextcloud-header.headers.stsSeconds=15552000'
      - 'traefik.http.middlewares.nextcloud-header.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.stsPreload=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.stsIncludeSubdomains=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.browserXssFilter=true'
      - 'traefik.http.middlewares.nextcloud-header.headers.customRequestHeaders.X-Forwarded-Proto=https'

  collabora:
    image: collabora/code
    container_name: collabora
    hostname: collabora
    restart: always
    environment:
      - TZ=${TZ}
      - aliasgroup1=${COLLABORA_ALIASGROUP1}
      - dictionaries=${COLLABORA_DICTIONARIES}
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
      #--o:net.wopi.host=cloud.your_domain.tld -> no need for this, as we are using the aliasgroup1
      - extra_params=${COLLABORA_EXTRA_PARAMS}
      - COLLABORA_HOST_NAME=${COLLABORA_HOST_NAME}    
    tty: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.collabora.tls=true'
      - 'traefik.http.routers.collabora.tls.certresolver=myresolver'
      - 'traefik.http.routers.collabora.entrypoints=websecure'
      - 'traefik.http.routers.collabora.rule=Host(`${COLLABORA_HOST_NAME}`)'
      - 'traefik.http.routers.collabora.middlewares=collabora-header'
      - 'traefik.http.services.collabora.loadbalancer.server.port=9980'
      - 'traefik.http.middlewares.collabora-header.headers.referrerPolicy=no-referrer'
      - 'traefik.http.middlewares.collabora-header.headers.stsSeconds=15552000'
      - 'traefik.http.middlewares.collabora-header.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.collabora-header.headers.stsPreload=true'
      - 'traefik.http.middlewares.collabora-header.headers.stsIncludeSubdomains=true'
      - 'traefik.http.middlewares.collabora-header.headers.browserXssFilter=true'
      - 'traefik.http.middlewares.collabora-header.headers.customRequestHeaders.X-Forwarded-Proto=https'
