log:
  level: DEBUG
accessLog:
    filePath: /var/log/traefik-access.log
api:
  dashboard: true
providers:
  docker:
    exposedByDefault: false
  file:
    # path to the (dynamic) configuration file
    # replace with a directory to watch for changes as recommended on https://doc.traefik.io/traefik/providers/file/
    filename: /etc/traefik/traefik_dynamic.yaml
    watch: true     
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

certificatesResolvers:
  myresolver:
    acme:      
      storage: /data/traefik/acme.json
      httpChallenge:
        entryPoint: web